{% set name = "dyson-equalizer" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dyson_equalizer-{{ version }}.tar.gz
  sha256: 9189bb6ac2fd6fc3a15b6f9af7da5dd7a4a6c401b7df7518cbbb746723c8f96b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core
    - flit-scm
    - pip
  run:
    - python >=3.10
    - matplotlib-base >=3.6
    - numpy >=1.25

test:
  imports:
    - dyson_equalizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KlugerLab/DysonEqualizer
  summary: Computes the Dyson Equalizer and related low rank approximation of the input data
  license: MIT
  license_file: LICENSE
  doc_url: https://klugerlab.github.io/DysonEqualizer/
  dev_url: https://github.com/KlugerLab/DysonEqualizer

extra:
  recipe-maintainers:
    - fra-pcmgf
